queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Build HUGO Page
pull_request_rules:
  - name: merge PRs labeled ready-to-merge
    conditions:
      - status-success=Build HUGO Page
      - label=ready-to-merge
    actions:
      queue:
        method: squash
        name: default
  - name: delete head branch on merged pull requests
    conditions:
      - merged
      - -head~=^(master|dev)$
      - -author~=^dependabot(|-preview)\[bot\]$
    actions:
      label:
        remove:
          - ready-to-merge
      delete_head_branch:
