language: node_js
node_js:
  - "stable"
env:
  matrix:
  - TEST_SUITE=lint
  - TEST_SUITE=build
  - TEST_SUITE=unit
  - TEST_SUITE=docs
matrix:
  exclude:
    - node_js: "8"
      env: TEST_SUITE=lint
    - node_js: "8"
      env: TEST_SUITE=docs
    - node_js: "8"
      env: TEST_SUITE=api-docs
    - node_js: "9"
      env: TEST_SUITE=lint
    - node_js: "9"
      env: TEST_SUITE=docs
    - node_js: "9"
      env: TEST_SUITE=api-docs
cache:
  directories:
  - node_modules
  - "$(npm config get prefix)/node_modules"
script:
- npm run test:$TEST_SUITE
after_success:
- ./coveralls_upload.sh
jobs:
  include:
  - stage: github pages release
    node_js: 'stable'
    script:
    - ng build --aot --prod --base-href=./
    - npm run prerender
    - yes | cp -rf ./dist/prerender ./dist/DonMahallem
    - cp ./dist/DonMahallem/index.html ./dist/DonMahallem/404.html
    if: branch = master
    deploy:
      provider: pages
      skip-cleanup: true
      local-dir: ./dist/DonMahallem
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      target_branch: master
      repo: donmahallem/donmahallem.github.io
      on:
        branch: master
  - stage: Publish docs on github
    node_js: stable
    script:
    - npm run compodoc
    if: branch = master
    deploy:
      provider: pages
      skip-cleanup: true
      local-dir: docs
      github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
      keep-history: true
      on:
        branch: master