baseURL: 'https://donmahallem.github.io/'
languageCode: en-us
title: My New Hugo Site
theme: PaperMod
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: github
      name: github
      url: 'https://github.com/donmahallem'
      weight: 30
params:
  editPost:
    URL: "https://github.com/donmahallem/donmahallem.github.io.source/tree/source/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
