name: Deploy Api to Github Pages
on:
  push:
    branches:
      - master
      - deployapi
  schedule:
    - cron: "0 */4 * * *"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Deploy Api Files
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: '14'
      - name: Setup Cache
        uses: actions/cache@v2.1.7
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node14-npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: |
          npm ci
      - name: Create Prerender List
        run: |
          npm run prepare:prerender
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: List Debug Information
        run: |
          ls -r -l ./src/assets
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: api # The branch the action should deploy to.
          folder: ./src/assets # The folder the action should deploy.
          target-folder: .
          CLEAN: true
          token: ${{ secrets.GITHUB_TOKEN }}
