name: Build Page

on: [push]

jobs:
  hugo:
    name: Build HUGO Page
    runs-on: ubuntu-18.04 # linux required if you want to use docker
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.0
      with:
        submodules: recursive
        persist-credentials: false
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Cache Repos Content
      id: cache-repos
      uses: actions/cache@v2.1.7
      with:
        path: content/repos
        key: ${{ steps.date.outputs.date }}-repos-${{ hashFiles('prerender.py') }}
    - name: Setup Python
      if: steps.cache-repos.outputs.cache-hit != 'true'
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install python requirements
      if: steps.cache-repos.outputs.cache-hit != 'true'
      run: pip install -r requirements.txt
    - name: Load Repositories
      if: steps.cache-repos.outputs.cache-hit != 'true'
      run: python prerender.py
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run Hugo
      if: github.ref != 'refs/heads/source'
      uses: docker://klakegg/hugo:0.93.2-ext-alpine-ci
      with:
        entrypoint: hugo
        args: --minify -D
    - name: Run Hugo
      if: github.ref == 'refs/heads/source'
      uses: docker://klakegg/hugo:0.93.2-ext-alpine-ci
      with:
        entrypoint: hugo
        args: --minify
    - name: Install SSH Client
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.APP_DEPLOY_KEY }}
    - name: Deploy 
      if: github.ref == 'refs/heads/source'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        SSH: true
        BRANCH: master # The branch the action should deploy to.
        FOLDER: public # The folder the action should deploy.
        REPOSITORY_NAME: donmahallem/donmahallem.github.io
        TARGET_FOLDER: .
        CLEAN: true
