name: Test
on: [push,pull_request]

jobs:
  test_suite:
    runs-on: ${{ matrix.os }}
    name: Test - ${{ matrix.os }} - Node ${{ matrix.node }}
    timeout-minutes: 30
    strategy:
      matrix:
        node: [12, 15]
        #os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node }}
      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - name: Setup Cache
        uses: actions/cache@v2.1.7
        with:
          path: |
            ${{ steps.npm-cache.outputs.dir }}
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node${{ matrix.node }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install Deps
        run: |
          npm ci
      - name: Run Build
        run: npm run build
      - name: Run Test
        run: npm run test
      - name: Run Lint
        run: npm run lint
      - name: Run Docs
        run: npm run docs
      - name: Create Prerender List
        run: |
          npm run prepare:prerender
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test Prerender
        timeout-minutes: 30
        run: |
          npm run prerender -- --routes-file ./prerender.txt
        env:
          API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  finish:
    needs: test_suite
    name: Finish Test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      run: echo "Finish"
